name: continuous deployment

on:
  push:
    branches: [production, qa]

jobs:
  setup:
    runs-on: [self-hosted, '${{ github.head_ref || github.ref_name }}']
    outputs:
      pm2_args: ${{ steps.pm2_args.outputs.args }}
    steps:
      - name: Set ecosystem config file path
        id: pm2_args
        run: echo "args=${{ github.workspace }}/.production/ecosystem.config.js --only backend-${{ github.head_ref || github.ref_name }}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Stop existing PM2 instance
        run: pm2 delete ${{ steps.pm2_args.outputs.args }}
        continue-on-error: true

  build_and_deploy:
    name: build_and_deploy
    needs: setup
    runs-on: [self-hosted, '${{ github.head_ref || github.ref_name }}']
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Start With PM2
        run: pm2 startOrReload ${{ needs.setup.outputs.pm2_args }}

      - name: Save PM2 State
        run: pm2 save
